### ISSUE TITLE
NPE when protocol missing

### ISSUE THREAD

**Issue by andrejserafim** [jcabi/jcabi-http#146]
The error reported by `JdkRequest` is rather poor when the protocol is missing, but the port is present.

```java
    @Test
    public final void fails() throws Exception {
        new JdkRequest("localhost:80").fetch();
    }
```

yields
```
java.lang.NullPointerException
	at com.jcabi.http.request.BaseRequest.<init>(BaseRequest.java:174)
	at com.jcabi.http.request.BaseRequest.<init>(BaseRequest.java:154)
	at com.jcabi.http.request.BaseRequest.<init>(BaseRequest.java:135)
	at com.jcabi.http.request.JdkRequest.<init>(JdkRequest.java:233)
...
```

In comparison 
```java
    @Test
    public final void fails() throws Exception {
        new JdkRequest("localhost").fetch();
    }
```
yields
```
java.net.MalformedURLException: no protocol: localhost

	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:91)
	at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:336)
	at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:251)
	at com.jcabi.http.request.JdkRequest.fetch(JdkRequest.java:268)
```

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by amihaiemil** [comment]
@yegor256 I could take this :D

**Comment by dmarkov** [comment]
@amihaiemil the task is yours (budget is 30 mins)

**Comment by amihaiemil** [comment]
@dmarkov PR #152 is for this issue

**Comment by dmarkov** [comment]
> @dmarkov PR #152 is for this issue

@amihaiemil thank you

**Comment by amihaiemil** [comment]
@dmarkov I need more time here. Seems like things are moving rather slowly

**Comment by dmarkov** [comment]
> @dmarkov I need more time here. Seems like things are moving rather slowly

@amihaiemil no problem, thanks for letting me know

**Comment by amihaiemil** [comment]
@andrejserafim pr was merged. Can u close this? :D

**Comment by andrejserafim** [comment]
@amihaiemil Thanks for fixing!

**Comment by dmarkov** [comment]
@amihaiemil Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-9TB62392JN0391332`, the task took 527 hours and 18 mins). added +30 to your rating, now it is equal to [+1001](http://www.netbout.com/b/36402?open=rating)
