### ISSUE TITLE
JdkRequest does not support PATCH

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-http#250]
```
Caused by: java.net.ProtocolException: Invalid HTTP method: PATCH
	at java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:440)
	at sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLConnection.java:553)
	at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:102)
	... 120 more
```

**Comment by VivekShahare04** [comment]
please provide me file @andreoss
