### ISSUE TITLE
maven dependency error for 2.0-SNAPSHOT

### ISSUE THREAD

**Issue by shashankrudra** [jcabi/jcabi-http#67]
I am using the below dependency and putting it in pom of a simple maven web project created using archetype-generate

```
<dependency>
      <groupId>com.jcabi</groupId>
      <artifactId>jcabi-http</artifactId>
      <version>2.0-SNAPSHOT</version>
    </dependency>

<repositories>
      <repository>
        <id>oss.sonatype.org</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      </repository>
    </repositories> 
```

Then I have a class with the below code 

```
public static void main(String[] args) throws IOException {
        JdkRequest jdkRequest = new JdkRequest("https://www.google.com");
        System.out.println(jdkRequest);
        String html;

        html = new JdkRequest("https://www.google.com")
          .uri().path("/users").queryParam("id", 333).back()
          .method(Request.GET)
          .header("Accept", "text/html")
          .fetch()
          .as(RestResponse.class)
          .assertStatus(HttpURLConnection.HTTP_OK)
          .body();

        System.out.println(html);
    }
```

It blows up on the very first line with error

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/core/UriBuilder
    at com.jcabi.http.request.BaseRequest.<init>(BaseRequest.java:148)
    at com.jcabi.http.request.BaseRequest.<init>(BaseRequest.java:126)
    at com.jcabi.http.request.JdkRequest.<init>(JdkRequest.java:231)
    at com.shashank.testJcabi.TestJcabiRequest.main(TestJcabiRequest.java:14)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.UriBuilder
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 4 more
```

Please suggest.

Thanks in advance !
Shashank

**Comment by yegor256** [comment]
@shashankrudra check this article http://http.jcabi.com/optional-dependencies.html

**Comment by shashankrudra** [comment]
thanks yegor ! 

It is better now however I am stuck at this last piece of that test code to work
.assertStatus(HttpURLConnection.HTTP_OK)

which jar version is this part of?

-
shashank

**Comment by yegor256** [comment]
@shashankrudra show your code please

**Comment by shashankrudra** [comment]
int httpOk = HttpURLConnection.HTTP_OK;
		
		String html = new JdkRequest("https://www.google.com")
		  .uri().path("/users").queryParam("id", new Integer(333)).back()
		  .method(Request.GET)
		  .header("Accept", "text/html")
		  .fetch()
		  .as(RestResponse.class)
		  .assertStatus(new Integer(httpOk))
		  .body();

and pom has most of the required dependency from the page you just suggested above.

thanks
shashank

**Comment by yegor256** [comment]
@shashankrudra and this code doesn't compile? btw, you don't need to wrap integers into `new Integer()`, just use scalar primitives

**Comment by yegor256** [comment]
@shashankrudra any news here? does it work?

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#67` is not assigned, can't get performer
