### ISSUE TITLE
OneMinuteWire doesn't terminate request after one minute

### ISSUE THREAD

**Issue by invisible-arrow** [jcabi/jcabi-http#80]
Version: 1.10.3
The request doesn't terminate after exceeding one minute.
From the stacktrace, it seems like it might be an aspect weaving problem, but I could be wrong.
Relevant thread state below:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.jcabi.http.wire.OneMinuteWire.send(OneMinuteWire.java:91)
	  at com.jcabi.http.wire.RetryWire.send(RetryWire.java:101)
	  at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:299)
	  at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:224)
```

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by invisible-arrow** [comment]
I see that with version 1.11+, we can configure the timeouts using the following:
`Request#timeout(int connect, int read)`
I'll close this ticket as it solves the original problem related to timeouts.
